apiVersion: apps/v1
kind: Deployment
metadata:
  name: skyline-app
  namespace: skyline
spec:
  replicas: 2
  selector:
    matchLabels:
      app: skyline-app
  template:
    metadata:
      labels:
        app: skyline-app
      annotations:
        ad.datadoghq.com/skyline-app.logs: '[{"source": "java", "service": "skyline-app"}]'
    spec:
      containers:
      - name: skyline-app
        image: 646558765106.dkr.ecr.ap-northeast-2.amazonaws.com/skyline-dev:latest
        ports:
        - containerPort: 8080
        env:
        - name: DD_AGENT_HOST
          valueFrom:
            fieldRef:
              fieldPath: status.hostIP
        - name: DD_TRACE_AGENT_PORT
          value: "8126"
        - name: DD_SERVICE
          value: "skyline-app"
        - name: DD_ENV
          value: "dev"
        - name: DD_VERSION
          value: "1.0"
        - name: DD_LOGS_INJECTION
          value: "true"
        - name: DD_TRACE_SAMPLE_RATE
          value: "1"
        resources:
          requests:
            memory: "1Gi"
            cpu: "500m"
          limits:
            memory: "2Gi"
            cpu: "1000m"
