apiVersion: apps/v1
kind: Deployment
metadata:
  name: skyline-app
  namespace: skyline
  labels:
    app: skyline
    component: backend
    version: v1.0.0
    tags.datadoghq.com/env: dev
    tags.datadoghq.com/service: skyline-app
    tags.datadoghq.com/version: v1.0.0
spec:
  replicas: 2
  selector:
    matchLabels:
      app: skyline
      component: backend
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: skyline
        component: backend
        version: v1.0.0
        tags.datadoghq.com/env: dev
        tags.datadoghq.com/service: skyline-app
        tags.datadoghq.com/version: v1.0.0
        admission.datadoghq.com/enabled: "true"
      annotations:
        admission.datadoghq.com/java-lib.version: v1.53.0
    spec:
      containers:
      - name: skyline
        image: 646558765106.dkr.ecr.ap-northeast-2.amazonaws.com/skyline-ojm:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        env:
        - name: DB_HOST
          valueFrom:
            secretKeyRef:
              key: DB_HOST
              name: skyline-db-secret
        - name: DB_PORT
          valueFrom:
            secretKeyRef:
              key: DB_PORT
              name: skyline-db-secret
        - name: DB_NAME
          valueFrom:
            secretKeyRef:
              key: DB_NAME
              name: skyline-db-secret
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              key: DB_USER
              name: skyline-db-secret
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              key: DB_PASSWORD
              name: skyline-db-secret
        - name: SPRING_PROFILES_ACTIVE
          value: production
        - name: SPRING_JPA_HIBERNATE_DDL_AUTO
          value: validate
        - name: SPRING_JPA_DEFER_DATASOURCE_INITIALIZATION
          value: "true"
        - name: SPRING_SQL_INIT_MODE
          value: always
        - name: SPRING_JPA_SHOW_SQL
          value: "true"
        - name: SERVER_ERROR_INCLUDE_STACKTRACE
          value: never
        - name: SERVER_ERROR_INCLUDE_MESSAGE
          value: never
        - name: DD_SERVICE
          value: skyline-app
        - name: DD_ENV
          value: dev
        - name: DD_VERSION
          value: v1.0.0
        - name: DD_LOGS_INJECTION
          value: "true"
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
          requests:
            cpu: 250m
            memory: 512Mi
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 90
          periodSeconds: 30
          timeoutSeconds: 10
          failureThreshold: 5
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 60
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 5
