# Generated by Amazon Q
resource "aws_eks_cluster" "main" {
  name     = "skyline-cluster"
  version  = "1.33"
}

resource "aws_eks_node_group" "main" {
  cluster_name   = aws_eks_cluster.main.name
  instance_types = ["t3.medium"]
  scaling_config {
    desired_size = 2
    max_size     = 4
    min_size     = 1
  }
}

resource "aws_db_instance" "main" {
  identifier     = "skyline-db"
  engine         = "mysql"
  instance_class = "db.t3.micro"
  db_name        = "skyline"
  username       = "skyline_ojm"
  password       = "skyline1267"
}
