# Generated by Amazon Q AI Agent
# AI Confidence: 0.95

resource "aws_eks_cluster" "skyline" {
  name     = "skyline-cluster"
  role_arn = aws_iam_role.eks_cluster.arn
  version  = "1.27"

  vpc_config {
    subnet_ids = [aws_subnet.private[*].id]
  }
}

resource "aws_eks_node_group" "skyline" {
  cluster_name    = aws_eks_cluster.skyline.name
  node_group_name = "skyline-nodes"
  node_role_arn   = aws_iam_role.eks_node_group.arn
  subnet_ids      = aws_subnet.private[*].id
  
  instance_types = ["t3.medium"]
  
  scaling_config {
    desired_size = 3
    max_size     = 5
    min_size     = 1
  }
}

resource "aws_rds_instance" "skyline" {
  identifier = "skyline-db"
  engine     = "mysql"
  instance_class = "db.t3.micro"
  allocated_storage = 20
  
  db_name  = "skyline"
  username = "admin"
  password = "changeme123!"
  
  skip_final_snapshot = true
}
