name: 🤖 AI Analysis

on:
  push:
    branches: [dev]
    paths: ['app/**']

jobs:
  ai-analysis:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install boto3
      run: pip install boto3
    
    - name: AI Analysis
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      run: |
        echo "🤖 AI Analysis for Skyline App"
        
        python3 << 'EOF'
import boto3
import json

try:
    print("Analyzing Skyline airline system with Amazon Q AI...")
    
    client = boto3.client('bedrock-runtime', region_name='ap-northeast-2')
    
    response = client.invoke_model(
        modelId='anthropic.claude-3-haiku-20240307-v1:0',
        body=json.dumps({
            "anthropic_version": "bedrock-2023-05-31",
            "max_tokens": 300,
            "messages": [{
                "role": "user", 
                "content": "Analyze Skyline airline reservation system (Spring Boot). Recommend: memory, CPU, replicas, database for EKS deployment."
            }]
        })
    )
    
    result = json.loads(response['body'].read())
    ai_response = result['content'][0]['text']
    
    print("SUCCESS! AI Analysis:")
    print("=" * 50)
    print(ai_response)
    print("=" * 50)
    
except Exception as e:
    print(f"Error: {e}")
    print("Using fallback analysis for Spring Boot app")
EOF
